# Generated by Django 5.2.5 on 2025-08-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vulnuser'),
        ('accounts', '0003_create_lab_users'),
    ]

    operations = [
    ]
